import type { Metadata } from 'next';
import '@/styles/css/globals.css';
import { ThemeProvider } from '@/components/Provider/Provider';

export const metadata: Metadata = {
    title: 'Weather App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
